// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yaml} from '../models';

export function FindControl(arg1:yaml.UIPackage,arg2:string):Promise<yaml.UIControl>;

export function GenerateYAML(arg1:yaml.UIPackage):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<yaml.FileData>;

export function ParseYAML(arg1:string):Promise<yaml.UIPackage>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetGameDataPath(arg1:string):Promise<void>;
