// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindControl(arg1, arg2) {
  return window['go']['main']['App']['FindControl'](arg1, arg2);
}

export function GenerateYAML(arg1) {
  return window['go']['main']['App']['GenerateYAML'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ParseYAML(arg1) {
  return window['go']['main']['App']['ParseYAML'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SetGameDataPath(arg1) {
  return window['go']['main']['App']['SetGameDataPath'](arg1);
}
